logging:
  level: DEBUG
  loggers:
    com.ajay.sampleApp: INFO
    org.hibernate.SQL: DEBUG
database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: ${DB_USER:-ajay}

  # the password
  password: ${DB_PASSWORD:-66132480}

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.show_sql: true

  # the JDBC URL
  url: jdbc:postgresql://${DB_HOST:-localhost}:${DB_PORT:-5432}/sample-app-2

redisHost: redis://${REDIS_HOST:-127.0.0.1}:${REDIS_PORT:-6379}

adminSecret: '66132480'
